Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Naming/VariableNumber:
  CheckSymbols: false

Metrics/BlockLength:
  Enabled: false
  # IgnoredMethods: ['context', 'describe', 'shared_examples_for']

Layout/LineLength:
  Max: 120
